# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: aws-nodejs # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs8.10

  region: ap-southeast-2

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - 
      Effect: "Allow"
      Action:
        - "dynamodb:*"
        - "appsync:GraphQL"
        - "iot:*"
      Resource: "*"

functions:
  recorder:
    handler: recorder/handler.main
    events:
      - iot:
          sql: "SELECT * FROM 'rmit'"
    environment:
      EVENT_TABLE_NAME:
        Ref: EventListDynamoDbTable
  publisher:
    handler: publisher/handler.main
    events:
      - iot:
          sql: "SELECT * FROM 'rmit'"
    environment:
      APPSYNC_API_KEY: da2-shsjzvnn4bgltg6kvwlen3py6y
      APPSYNC_HOST: pcqs3omaljbghgj5cf7jfmykyi.appsync-api.ap-southeast-2.amazonaws.com
      APPSYNC_REGION: ap-southeast-2
  get-latest:
    handler: get-latest/handler.main
    events:
      - http:
          path: /latest
          method: get
          cors: true
    environment:
      EVENT_TABLE_NAME:
        Ref: EventListDynamoDbTable

# you can add CloudFormation resource templates here
resources:
 Resources:
    ScalingRole: 
      Type: "AWS::IAM::Role"
      Properties: 
        AssumeRolePolicyDocument: 
          Version: "2012-10-17"
          Statement: 
          - 
            Effect: Allow
            Principal: 
              Service: 
                - 
                  "application-autoscaling.amazonaws.com"
            Action: 
            - 
              "sts:AssumeRole"
        Path: "/"
        Policies: 
          - 
            PolicyName: root
            PolicyDocument: 
              Version: "2012-10-17"
              Statement: 
              - 
                Effect: Allow
                Action:          
                - "dynamodb:DescribeTable"
                - "dynamodb:UpdateTable"
                - "cloudwatch:PutMetricAlarm"
                - "cloudwatch:DescribeAlarms"
                - "cloudwatch:GetMetricStatistics"
                - "cloudwatch:SetAlarmState"
                - "cloudwatch:DeleteAlarms"
                Resource: "*"
    EventListDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        AttributeDefinitions:
          -
            AttributeName: groupingKey
            AttributeType: S
          -
            AttributeName: timestamp
            AttributeType: N
        KeySchema:
          -
            AttributeName: groupingKey
            KeyType: HASH
          -
            AttributeName: timestamp
            KeyType: RANGE
    EventListTableWriteCapacityScalableTarget: 
      Type: "AWS::ApplicationAutoScaling::ScalableTarget"
      Properties: 
        MaxCapacity: 100
        MinCapacity: 5
        ResourceId:
          Fn::Join:
            - "/"
            - - table
              -
                Ref: EventListDynamoDbTable
        RoleARN: 
          Fn::GetAtt: ScalingRole.Arn
        ScalableDimension: "dynamodb:table:WriteCapacityUnits"
        ServiceNamespace: dynamodb
    EventListTableWriteScalingPolicy: 
      Type: "AWS::ApplicationAutoScaling::ScalingPolicy"
      Properties: 
        PolicyName: WriteAutoScalingPolicy
        PolicyType: TargetTrackingScaling
        ScalingTargetId: 
          Ref: EventListTableWriteCapacityScalableTarget
        TargetTrackingScalingPolicyConfiguration: 
          TargetValue: 70
          ScaleInCooldown: 60
          ScaleOutCooldown: 60
          PredefinedMetricSpecification: 
            PredefinedMetricType: DynamoDBWriteCapacityUtilization
    EventListTableReadCapacityScalableTarget: 
      Type: "AWS::ApplicationAutoScaling::ScalableTarget"
      Properties: 
        MaxCapacity: 100
        MinCapacity: 5
        ResourceId:
          Fn::Join:
            - "/"
            - - table
              -
                Ref: EventListDynamoDbTable
        RoleARN: 
          Fn::GetAtt: ScalingRole.Arn
        ScalableDimension: "dynamodb:table:ReadCapacityUnits"
        ServiceNamespace: dynamodb
    EventListTableReadScalingPolicy: 
      Type: "AWS::ApplicationAutoScaling::ScalingPolicy"
      Properties: 
        PolicyName: ReadAutoScalingPolicy
        PolicyType: TargetTrackingScaling
        ScalingTargetId: 
          Ref: EventListTableReadCapacityScalableTarget
        TargetTrackingScalingPolicyConfiguration: 
          TargetValue: 70
          ScaleInCooldown: 60
          ScaleOutCooldown: 60
          PredefinedMetricSpecification: 
            PredefinedMetricType: DynamoDBReadCapacityUtilization
 Outputs:
